### ISSUE TITLE
Windows Platform is not supported.

### ISSUE THREAD

**Issue by DxsSucuk** [LuckyDucko/Mopups#74]
Its being stated that Mopups has support for Windows in the ReadMe, but when trying to display a Popup you a greated with a PlatformNotSupportedException.

**Comment by DavidABJ13** [comment]
I have the same issue in Windows with version 1.1.1, try downgrading to 1.1.0 version, this works for me.

**Comment by mapanjwani** [comment]
Any ETA on when will it be resolved for latest version?

**Comment by HNordhaus** [comment]
The reason for the missing "Windows" support is simply a compilation error that prevents the Windows part from ending up in the released NuGet.

You can "easily" help yourself, or ask the maintainer to simply build a new version, since the current source code (**master**) already contains the necessary fix and otherwise corresponds to version 1.1.1, even if the version number is 1.1.0 🤷‍♂️

So there are two options:

- The maintainer creates a new release from the current master-branch, e.g. as version 1.1.1.1, and makes it available that way.
- You download the code, compile it and get a NuGet, which should work then.

I hope this helps, but anyway I doubt it has a great future since the project does not seem to be maintained anymore 😢

Kind regards
Henrik

**Comment by ZeProgFactory** [comment]
See also #78

**Comment by LuckyDucko** [comment]
As i no longer truly do any mobile dev work, the time i used to put into this has gone away.

I did make a new release, including some other previous work i have done. I may get back into maintaining this, just as an exercise to keep my head in the mobile dev space a little longer. 

Can you guys test and let me know?

**Comment by DxsSucuk** [comment]
Yep latest release seem to have fixed it!
